apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: fic-gig
  labels:
    name: web-ingress
spec:
  # tls:
  #   - hosts:
  #     - fictional-giggle.com
  #     secretName: fic-gig-tls
  rules:
    - host: fictional-giggle.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: fictional-giggle-web-service
                port: 
                  number: 3000
